services:
  nginx:
    image: jaouad3243/scrumflow-nginx:latest
    container_name: scrumflow-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
      - ai-system
    networks:
      - scrumflow-network

  db:
    image: postgres:15-alpine
    container_name: scrumflow-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scrumflow-network

  backend:
    image: jaouad3243/scrumflow-backend:latest
    container_name: scrumflow-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend.env
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - scrumflow-network

  frontend:
    image: jaouad3243/scrumflow-frontend:latest
    container_name: scrumflow-frontend
    restart: always
    env_file:
      - ./frontend.env
    networks:
      - scrumflow-network

  ai-system:
    image: jaouad3243/scrumflow-ai:latest
    container_name: scrumflow-ai
    restart: always
    networks:
      - scrumflow-network

networks:
  scrumflow-network:
    driver: bridge

volumes:
  postgres_data:
